# Generated by Django 6.0 on 2025-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryModel',
            fields=[
                ('hash', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('abc_def', models.PositiveSmallIntegerField(verbose_name='Код')),
                ('range_from', models.PositiveSmallIntegerField(db_index=True, verbose_name='Диапозон от')),
                ('range_to', models.PositiveSmallIntegerField(db_index=True, verbose_name='Диапозон до')),
                ('capacity', models.PositiveIntegerField(verbose_name='Емкость')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('territory', models.CharField(max_length=255, verbose_name='Территория ГАР')),
                ('inn', models.CharField(max_length=255, verbose_name='INN')),
            ],
            options={
                'indexes': [models.Index(fields=['abc_def', 'range_from', 'range_to'], name='base_regist_abc_def_6fb8f4_idx')],
            },
        ),
    ]
