# Generated by Django 6.0 on 2025-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrymodel',
            name='abc_def',
            field=models.PositiveIntegerField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='range_from',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Диапозон от'),
        ),
        migrations.AlterField(
            model_name='registrymodel',
            name='range_to',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Диапозон до'),
        ),
    ]
